const peliculas = [
    {
      id: 1,
      titulo: "The Shawshank Redemption",
      generos: ["Drama"],
      anio: 1994,
      director: "Frank Darabont",
      likes: 1850,
      portada: "https://m.media-amazon.com/images/I/51NiGlapXlL._AC_.jpg",
    },
    {
      id: 2,
      titulo: "The Godfather",
      generos: ["Crime", "Drama"],
      anio: 1972,
      director: "Francis Ford Coppola",
      likes: 2100,
      portada: "https://m.media-amazon.com/images/I/41+eK8zBwQL._AC_.jpg",
    },
    {
      id: 3,
      titulo: "The Dark Knight",
      generos: ["Action", "Crime", "Drama"],
      anio: 2008,
      director: "Christopher Nolan",
      likes: 2800,
      portada: "https://m.media-amazon.com/images/I/51k0qa6zY-L._AC_.jpg",
    },
    {
      id: 4,
      titulo: "Pulp Fiction",
      generos: ["Crime", "Drama"],
      anio: 1994,
      director: "Quentin Tarantino",
      likes: 1700,
      portada: "https://m.media-amazon.com/images/I/51V5ZpFyaFL._AC_.jpg",
    },
    {
      id: 5,
      titulo: "Inception",
      generos: ["Action", "Adventure", "Sci-Fi"],
      anio: 2010,
      director: "Christopher Nolan",
      likes: 2600,
      portada: "https://m.media-amazon.com/images/I/5101fG3r+SL._AC_.jpg",
    },
    {
      id: 6,
      titulo: "Fight Club",
      generos: ["Drama"],
      anio: 1999,
      director: "David Fincher",
      likes: 1900,
      portada: "https://m.media-amazon.com/images/I/5190M4JGkRL._AC_.jpg",
    },
    {
      id: 7,
      titulo: "Forrest Gump",
      generos: ["Drama", "Romance"],
      anio: 1994,
      director: "Robert Zemeckis",
      likes: 2400,
      portada: "https://m.media-amazon.com/images/I/41cMxNsyfqL._AC_.jpg",
    },
    {
      id: 8,
      titulo: "The Matrix",
      generos: ["Action", "Sci-Fi"],
      anio: 1999,
      director: "Lana Wachowski, Lilly Wachowski",
      likes: 2200,
      portada: "https://m.media-amazon.com/images/I/51vpnbwFHrL._AC_.jpg",
    },
    {
      id: 9,
      titulo: "Interstellar",
      generos: ["Adventure", "Drama", "Sci-Fi"],
      anio: 2014,
      director: "Christopher Nolan",
      likes: 2500,
      portada: "https://m.media-amazon.com/images/I/81kEwrIXsfL._AC_SL1500_.jpg",
    },
    {
      id: 10,
      titulo: "Gladiator",
      generos: ["Action", "Adventure", "Drama"],
      anio: 2000,
      director: "Ridley Scott",
      likes: 1800,
      portada: "https://m.media-amazon.com/images/I/51A9FjO5hFL._AC_.jpg",
    },
    {
      id: 11,
      titulo: "Titanic",
      generos: ["Drama", "Romance"],
      anio: 1997,
      director: "James Cameron",
      likes: 2300,
      portada: "https://m.media-amazon.com/images/I/51rOnIjLqzL._AC_.jpg",
    },
    {
      id: 12,
      titulo: "The Lord of the Rings: The Fellowship of the Ring",
      generos: ["Adventure", "Drama", "Fantasy"],
      anio: 2001,
      director: "Peter Jackson",
      likes: 2600,
      portada: "https://m.media-amazon.com/images/I/51Qvs9i5a%2BL._AC_.jpg",
    },
    {
      id: 13,
      titulo: "The Silence of the Lambs",
      generos: ["Crime", "Drama", "Thriller"],
      anio: 1991,
      director: "Jonathan Demme",
      likes: 1700,
      portada: "https://m.media-amazon.com/images/I/41n4xXat93L._AC_.jpg",
    },
    {
      id: 14,
      titulo: "Saving Private Ryan",
      generos: ["Drama", "War"],
      anio: 1998,
      director: "Steven Spielberg",
      likes: 2100,
      portada: "https://m.media-amazon.com/images/I/51k0qa6zY-L._AC_.jpg",
    },
    {
      id: 15,
      titulo: "The Green Mile",
      generos: ["Crime", "Drama", "Fantasy"],
      anio: 1999,
      director: "Frank Darabont",
      likes: 1800,
      portada: "https://m.media-amazon.com/images/I/51zUbui+gbL._AC_.jpg",
    },
    {
      id: 16,
      titulo: "Whiplash",
      generos: ["Drama", "Music"],
      anio: 2014,
      director: "Damien Chazelle",
      likes: 1700,
      portada: "https://m.media-amazon.com/images/I/71t6l4UttwL._AC_SY679_.jpg",
    },
    {
      id: 17,
      titulo: "The Departed",
      generos: ["Crime", "Drama", "Thriller"],
      anio: 2006,
      director: "Martin Scorsese",
      likes: 1600,
      portada: "https://m.media-amazon.com/images/I/51L8fLqDFTL._AC_.jpg",
    },
    {
      id: 18,
      titulo: "Joker",
      generos: ["Crime", "Drama", "Thriller"],
      anio: 2019,
      director: "Todd Phillips",
      likes: 2300,
      portada: "https://m.media-amazon.com/images/I/71hZEGH8TPL._AC_SL1111_.jpg",
    },
    {
      id: 19,
      titulo: "Parasite",
      generos: ["Comedy", "Drama", "Thriller"],
      anio: 2019,
      director: "Bong Joon-ho",
      likes: 2100,
      portada: "https://m.media-amazon.com/images/I/91nPthc8LfL._AC_SL1500_.jpg",
    },
    {
      id: 20,
      titulo: "The Prestige",
      generos: ["Drama", "Mystery", "Sci-Fi"],
      anio: 2006,
      director: "Christopher Nolan",
      likes: 1900,
      portada: "https://m.media-amazon.com/images/I/51hQ9xuz5tL._AC_.jpg",
    },
    {
      id: 21,
      titulo: "The Social Network",
      generos: ["Biography", "Drama"],
      anio: 2010,
      director: "David Fincher",
      likes: 1600,
      portada: "https://m.media-amazon.com/images/I/51rggtPgmRL._AC_.jpg",
    },
    {
      id: 22,
      titulo: "Avengers: Endgame",
      generos: ["Action", "Adventure", "Drama"],
      anio: 2019,
      director: "Anthony Russo, Joe Russo",
      likes: 3000,
      portada: "https://m.media-amazon.com/images/I/81ExhpBEbHL._AC_SY679_.jpg",
    },
    {
      id: 23,
      titulo: "La La Land",
      generos: ["Comedy", "Drama", "Music"],
      anio: 2016,
      director: "Damien Chazelle",
      likes: 1800,
      portada: "https://m.media-amazon.com/images/I/91KkWf50SoL._AC_SL1500_.jpg",
    },
    {
      id: 24,
      titulo: "Django Unchained",
      generos: ["Drama", "Western"],
      anio: 2012,
      director: "Quentin Tarantino",
      likes: 2000,
      portada: "https://m.media-amazon.com/images/I/81et2Am2WoL._AC_SY679_.jpg",
    },
    {
      id: 25,
      titulo: "Coco",
      generos: ["Animation", "Adventure", "Family"],
      anio: 2017,
      director: "Lee Unkrich",
      likes: 1900,
      portada: "https://m.media-amazon.com/images/I/81zueDN9pEL._AC_SY679_.jpg",
    },
    {
      id: 26,
      titulo: "WALL·E",
      generos: ["Animation", "Adventure", "Family"],
      anio: 2008,
      director: "Andrew Stanton",
      likes: 1800,
      portada: "https://m.media-amazon.com/images/I/71RbH0jhTCL._AC_SY679_.jpg",
    },
    {
      id: 27,
      titulo: "The Lion King",
      generos: ["Animation", "Adventure", "Drama"],
      anio: 1994,
      director: "Roger Allers, Rob Minkoff",
      likes: 2500,
      portada: "https://m.media-amazon.com/images/I/81s6DUyQCZL._AC_SL1500_.jpg",
    },
    {
      id: 28,
      titulo: "Toy Story",
      generos: ["Animation", "Adventure", "Comedy"],
      anio: 1995,
      director: "John Lasseter",
      likes: 2000,
      portada: "https://m.media-amazon.com/images/I/81A-8l3j5qL._AC_SY679_.jpg",
    },
    {
      id: 29,
      titulo: "Shrek",
      generos: ["Animation", "Adventure", "Comedy"],
      anio: 2001,
      director: "Andrew Adamson, Vicky Jenson",
      likes: 2100,
      portada: "https://m.media-amazon.com/images/I/81LGhP1FZfL._AC_SY679_.jpg",
    },
    {
      id: 30,
      titulo: "Spider-Man: Into the Spider-Verse",
      generos: ["Animation", "Action", "Adventure"],
      anio: 2018,
      director: "Bob Persichetti, Peter Ramsey, Rodney Rothman",
      likes: 2200,
      portada: "https://m.media-amazon.com/images/I/91kFYg4fX3L._AC_SY679_.jpg",
    },
  ];
  export default peliculas;